version: '3'

services:
  web:
    build: .
    command: /bin/bash -c "rm tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    env_file: .env.dev
    volumes:
    - .:/app
    ports:
    - "3000:3000"
#  postgres-data:
#    image: busybox
#    volumes:
#    - ~/postgresql/data
#    container_name: postgres-datastore
#
#  postgresql:
#    image: postgres
#    environment:
#      POSTGRES_USER: hoge
#      POSTGRES_PASSWORD: password
#    ports:
#    - "5432:5432"
#    container_name: postgres-db
#    volumes_from:
#    - postgres-data
#
#
